baseURL = "https://gloomist805.github.io/Blog/"
languageCode = "zh-cn"
title = "一人行者"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true

  # 首页开启文章显示
  showPosts = true
  homePostLimit = 3

[params.profileMode]
  enabled = true
  title = "欢迎来到伤心镇"
  subtitle = "Gloomist的博客，记录、随想、求索。"
  buttons = []
  showPosts = true
  postAmount = 3

[[menu.main]]
  name = "主页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "文章"
  url = "/archives/"
  weight = 2

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 3

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 4

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 5
