baseURL = "https://gloomist805.github.io/Blog/"
languageCode = "zh-cn"
title = "一人行者"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  disableThemeToggle = false

[[menu.main]]
  identifier = "home"
  name = "主页"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "archives"
  name = "文章"
  url = "/archives/"
  weight = 2

[[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  weight = 3

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 4

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 5


