baseURL = "https://gloomist805.github.io/Blog/"
languageCode = "zh-cn"
title = "一人行者"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = true


  # 首页开启文章显示
  showPosts = true
  homePostLimit = 3

[params.profileMode]
  enabled = false
 
[[menu.main]]
  name = "主页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "文章"
  url = "/archives/"
  weight = 2

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 3

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 4

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 5
